notifications:
  email: false

language: node_js

node_js:
  - "8"

script:
  - npm run build

before_deploy:
  - npm run build

deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "faviator-xyz"
